[2025-04-16 02:23:22,872 W 67299 67299] gcs_rpc_client.h:148: Failed to connect to GCS at address v006:6379 within 5 seconds.
[2025-04-16 02:23:52,889 W 67299 67299] gcs_client.cc:178: Failed to get cluster ID from GCS server: TimedOut: Timed out while waiting for GCS to become available.
[2025-04-16 02:23:58,897 W 67299 67299] gcs_rpc_client.h:148: Failed to connect to GCS at address v006:6379 within 5 seconds.
[2025-04-16 02:24:28,900 W 67299 67299] gcs_client.cc:178: Failed to get cluster ID from GCS server: TimedOut: Timed out while waiting for GCS to become available.
[2025-04-16 02:24:34,905 W 67299 67299] gcs_rpc_client.h:148: Failed to connect to GCS at address v006:6379 within 5 seconds.
[2025-04-16 02:25:04,909 W 67299 67299] gcs_client.cc:178: Failed to get cluster ID from GCS server: TimedOut: Timed out while waiting for GCS to become available.
[2025-04-16 02:25:10,914 W 67299 67299] gcs_rpc_client.h:148: Failed to connect to GCS at address v006:6379 within 5 seconds.
[2025-04-16 02:25:40,917 W 67299 67299] gcs_client.cc:178: Failed to get cluster ID from GCS server: TimedOut: Timed out while waiting for GCS to become available.
[2025-04-16 02:25:46,922 W 67299 67299] gcs_rpc_client.h:148: Failed to connect to GCS at address v006:6379 within 5 seconds.
[2025-04-16 02:26:16,926 W 67299 67299] gcs_client.cc:178: Failed to get cluster ID from GCS server: TimedOut: Timed out while waiting for GCS to become available.
[2025-04-16 02:26:22,931 W 67299 67299] gcs_rpc_client.h:148: Failed to connect to GCS at address v006:6379 within 5 seconds.
[2025-04-16 02:26:52,934 W 67299 67299] gcs_client.cc:178: Failed to get cluster ID from GCS server: TimedOut: Timed out while waiting for GCS to become available.
[2025-04-16 02:26:58,939 W 67299 67299] gcs_rpc_client.h:148: Failed to connect to GCS at address v006:6379 within 5 seconds.
[2025-04-16 02:27:28,942 W 67299 67299] gcs_client.cc:178: Failed to get cluster ID from GCS server: TimedOut: Timed out while waiting for GCS to become available.
[2025-04-16 02:27:34,947 W 67299 67299] gcs_rpc_client.h:148: Failed to connect to GCS at address v006:6379 within 5 seconds.
[2025-04-16 02:28:04,950 W 67299 67299] gcs_client.cc:178: Failed to get cluster ID from GCS server: TimedOut: Timed out while waiting for GCS to become available.
[2025-04-16 02:28:10,954 W 67299 67299] gcs_rpc_client.h:148: Failed to connect to GCS at address v006:6379 within 5 seconds.
[2025-04-16 02:28:40,958 W 67299 67299] gcs_client.cc:178: Failed to get cluster ID from GCS server: TimedOut: Timed out while waiting for GCS to become available.
[2025-04-16 02:28:46,961 W 67299 67299] gcs_rpc_client.h:148: Failed to connect to GCS at address v006:6379 within 5 seconds.
[2025-04-16 02:29:16,965 W 67299 67299] gcs_client.cc:178: Failed to get cluster ID from GCS server: TimedOut: Timed out while waiting for GCS to become available.
[2025-04-16 02:29:22,970 W 67299 67299] gcs_rpc_client.h:148: Failed to connect to GCS at address v006:6379 within 5 seconds.
[2025-04-16 02:29:52,974 W 67299 67299] gcs_client.cc:178: Failed to get cluster ID from GCS server: TimedOut: Timed out while waiting for GCS to become available.
[2025-04-16 02:29:58,978 W 67299 67299] gcs_rpc_client.h:148: Failed to connect to GCS at address v006:6379 within 5 seconds.
[2025-04-16 02:30:28,981 W 67299 67299] gcs_client.cc:178: Failed to get cluster ID from GCS server: TimedOut: Timed out while waiting for GCS to become available.
[2025-04-16 02:30:34,986 W 67299 67299] gcs_rpc_client.h:148: Failed to connect to GCS at address v006:6379 within 5 seconds.
[2025-04-16 02:31:04,990 W 67299 67299] gcs_client.cc:178: Failed to get cluster ID from GCS server: TimedOut: Timed out while waiting for GCS to become available.
[2025-04-16 02:31:10,994 W 67299 67299] gcs_rpc_client.h:148: Failed to connect to GCS at address v006:6379 within 5 seconds.
[2025-04-16 02:31:40,998 W 67299 67299] gcs_client.cc:178: Failed to get cluster ID from GCS server: TimedOut: Timed out while waiting for GCS to become available.
[2025-04-16 02:31:47,002 W 67299 67299] gcs_rpc_client.h:148: Failed to connect to GCS at address v006:6379 within 5 seconds.
[2025-04-16 02:32:17,005 W 67299 67299] gcs_client.cc:178: Failed to get cluster ID from GCS server: TimedOut: Timed out while waiting for GCS to become available.
[2025-04-16 02:32:23,011 W 67299 67299] gcs_rpc_client.h:148: Failed to connect to GCS at address v006:6379 within 5 seconds.
[2025-04-16 02:32:53,014 W 67299 67299] gcs_client.cc:178: Failed to get cluster ID from GCS server: TimedOut: Timed out while waiting for GCS to become available.
[2025-04-16 02:32:59,019 W 67299 67299] gcs_rpc_client.h:148: Failed to connect to GCS at address v006:6379 within 5 seconds.
[2025-04-16 02:33:29,022 W 67299 67299] gcs_client.cc:178: Failed to get cluster ID from GCS server: TimedOut: Timed out while waiting for GCS to become available.
[2025-04-16 02:33:35,027 W 67299 67299] gcs_rpc_client.h:148: Failed to connect to GCS at address v006:6379 within 5 seconds.
[2025-04-16 02:34:05,031 W 67299 67299] gcs_client.cc:178: Failed to get cluster ID from GCS server: TimedOut: Timed out while waiting for GCS to become available.
[2025-04-16 02:34:11,036 W 67299 67299] gcs_rpc_client.h:148: Failed to connect to GCS at address v006:6379 within 5 seconds.
[2025-04-16 02:34:41,040 W 67299 67299] gcs_client.cc:178: Failed to get cluster ID from GCS server: TimedOut: Timed out while waiting for GCS to become available.
[2025-04-16 02:34:47,043 W 67299 67299] gcs_rpc_client.h:148: Failed to connect to GCS at address v006:6379 within 5 seconds.
[2025-04-16 02:35:17,047 W 67299 67299] gcs_client.cc:178: Failed to get cluster ID from GCS server: TimedOut: Timed out while waiting for GCS to become available.
Traceback (most recent call last):
  File "/jet/home/ztong/.conda/envs/vllm_env/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/jet/home/ztong/.conda/envs/vllm_env/lib/python3.10/site-packages/ray/scripts/scripts.py", line 2691, in main
    return cli()
  File "/jet/home/ztong/.conda/envs/vllm_env/lib/python3.10/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/jet/home/ztong/.conda/envs/vllm_env/lib/python3.10/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/jet/home/ztong/.conda/envs/vllm_env/lib/python3.10/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/jet/home/ztong/.conda/envs/vllm_env/lib/python3.10/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/jet/home/ztong/.conda/envs/vllm_env/lib/python3.10/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/jet/home/ztong/.conda/envs/vllm_env/lib/python3.10/site-packages/ray/autoscaler/_private/cli_logger.py", line 823, in wrapper
    return f(*args, **kwargs)
  File "/jet/home/ztong/.conda/envs/vllm_env/lib/python3.10/site-packages/ray/scripts/scripts.py", line 1049, in start
    node = ray._private.node.Node(
  File "/jet/home/ztong/.conda/envs/vllm_env/lib/python3.10/site-packages/ray/_private/node.py", line 159, in __init__
    self._init_gcs_client()
  File "/jet/home/ztong/.conda/envs/vllm_env/lib/python3.10/site-packages/ray/_private/node.py", line 778, in _init_gcs_client
    raise RuntimeError(
RuntimeError: Failed to connect to GCS. Last connection error: Traceback (most recent call last):
  File "/jet/home/ztong/.conda/envs/vllm_env/lib/python3.10/site-packages/ray/_private/node.py", line 741, in _init_gcs_client
    client = GcsClient(
  File "python/ray/_raylet.pyx", line 2719, in ray._raylet.GcsClient.__cinit__
  File "python/ray/includes/gcs_client.pxi", line 65, in ray._raylet.InnerGcsClient.standalone
  File "python/ray/includes/common.pxi", line 118, in ray._raylet.check_status_timeout_as_rpc_error
ray.exceptions.RpcError: Timed out while waiting for GCS to become available.

2025-04-16 02:35:58,684	INFO worker.py:1841 -- Started a local Ray instance.
